org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.1-beta

core_version = 2.0.5-26072200

## Mod Properties
mod_id=cores
mod_name=Cores
mod_license=AM-CC-0
mod_version=26.2-2.0.5-26072201-Neo
mod_group_id=dev.anye.mc
mod_authors=[AnYe]AnMao(s)
